// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btsdrsvmoonnxqedfhgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0c2Ryc3Ztb29ubnhxZWRmaGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDY0NjgsImV4cCI6MjA2ODMyMjQ2OH0.IBKAs4guVD25DfeEsWs1EvsZZ2mxyqKcLb2AS-U9_XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});